
[package]
name = "solders-transaction-status-enums"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders transaction status enums crate."

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
solders-macros = { workspace = true }
