
[package]
name = "solders-system-program"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders system program crate."

[dependencies]
bincode = { workspace = true }
derive_more = { workspace = true }
dict_derive = "0.6.0"
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
solana-address-lookup-table-interface = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-system-interface = { workspace = true }
solders-instruction = { workspace = true }
solders-macros = { workspace = true }
solders-pubkey = { workspace = true }
solders-traits = { workspace = true }
solders-traits-core = { workspace = true }
