
[package]
name = "solders-traits"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
description = "A collection of traits and helpers for Solders."
license = { workspace = true }
repository = { workspace = true }

[dependencies]
pyo3 = { workspace = true }
solana-commitment-config = { workspace = true }
solana-hash = { workspace = true }
solana-pubkey = { workspace = true }
solana-sanitize = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-transaction-error = { workspace = true }
bincode = { workspace = true }
litesvm = { workspace = true, optional = true }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
solders-traits-core = { workspace = true }
solana-banks-client = { workspace = true, optional = true }

[features]
banks-client = ["dep:solana-banks-client"]
litesvm = ["dep:litesvm"]
